app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::resource('admin/users', 'AdminUsersController');

routes/web.php
<?php

use App\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });

// Route::get('verify/{email}/{verifyToken}','Auth\RegisterController@sendEmailDone')->name('sendEmailDone');

Route::get('verify/{email}/{verifyToken}',function($email, $verifyToken){

	$user = User::where('email',$email)->first();
        
    if($user){
        user::where('email',$email)->update(['is_active'=>'1', 'verifyToken'=>null]);

        Session::flash('success_validar_email', 'Conta ativada com sucesso!');

        return redirect('/');

    }else{
        return 'erro';
    }
})->name('sendEmailDone');

Route::auth();

Route::get('/', 'IndexController@index');

Route::get('/home', 'IndexController@index');

Route::middleware(['inscrito'])->group(function () {
    Route::get('user', 'UserController@index');
    Route::get('user/edit', 'UserController@edit');
    Route::get('user/update', 'UserController@update');
    Route::resource('user', 'UserController');
});

Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['middleware'=>'admin'], function(){
	
	Route::get('/admin', 'AdminController@index');

	Route::resource('admin/users', 'AdminUsersController');

	Route::resource('admin/redessociais', 'RedesSociaisController');

	Route::resource('admin/posts', 'AdminPostsController');

	Route::resource('admin/categories', 'AdminCategoriesController');

	Route::resource('admin/comments', 'PostCommentsController');

	Route::resource('admin/comment/replies', 'CommentRepliesController');

	Route::resource('admin/quemsomos', 'QuemSomosController');

});

Route::get('/post/{id}', ['as'=>'home.post', 'uses'=>'AdminPostsController@post']); // as nomeia a rota

Route::get('send', 'ContatoController@send');

Route::get('fale_conosco',function(){

	return view('fale_conosco');
});

Route::post('enviar', 'ContatoController@enviaContato');


Route::get('/curtir_post/', ['as'=>'curtir_post', 'uses'=>'UserController@curtir']); // as nomeia a rota

Route::get('/descurtir_post', ['as'=>'descurtir_post', 'uses'=>'UserController@descurtir']); // as nomeia a rota


Route::resource('comments', 'PostCommentsController');

Route::resource('replies', 'CommentRepliesController');

Route::resource('comments', 'PostCommentsController');

Route::get('/category/{id}', ['as'=>'category', 'uses'=>'IndexController@categories']); // as nomeia a rota

Route::get('/quemsomos', ['as'=>'quemsomos', 'uses'=>'IndexController@index_quemsomos']); // as nomeia a rota

Route::post('/more_posts', 'IndexController@more_posts');


Route::get('search_ajax_post', 'IndexController@search_ajax_post');

Route::get('/search_post/', ['as'=>'search_post','uses'=>'IndexController@search_post']);

//Routes to social login
Route::post('/login/social', 'Auth\LoginController@loginSocial');

Route::get('/login/callback', 'Auth\LoginController@loginCallback');

resources/views/admin/index.blade.php
@extends('layouts.admin')

@section('content')

	<h1>Visualizações</h1>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<canvas id="myChart"></canvas>
		</div>
	</div>

	<h1>Posts mais Visualizados</h1>

	@if($posts_famosos)
	    @foreach ($posts_famosos as $post)

	    	<div class="panel panel-default">
                <div class="panel-body">
                	<h4><a href="{{url('/post', $post->id)}}"><b>{{$post->title}}</b></a> </h4>
	    			<small><i class="fa fa-user"></i> <a href="{{route('user.show', $post->user->id)}}"> <b>{{$post->user->name}}</b></a></small><br>
                    <small><i class="fa fa-eye"></i> {{$post->views_post->count()}}</small>
	    		</div>
	    	</div>	    	

	    @endforeach
	@endif

	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>

	<script type="text/javascript">

		var hoje = new Date();
		var hoje_1 = new Date();
		var hoje_2 = new Date();
		var hoje_3 = new Date();
		var hoje_4 = new Date();

		var days = ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab"];

		hoje = hoje.getDate() + " " + days[hoje.getDay()];

		hoje_1.setDate(hoje_1.getDate() - 1);

		hoje_1 = hoje_1.getDate() + " " + days[hoje_1.getDay()];

		hoje_2.setDate(hoje_2.getDate() - 2);

		hoje_2 = hoje_2.getDate() + " " + days[hoje_2.getDay()];

		hoje_3.setDate(hoje_3.getDate() - 3);

		hoje_3 = hoje_3.getDate() + " " + days[hoje_3.getDay()];

		hoje_4.setDate(hoje_4.getDate() - 4);

		hoje_4 = hoje_4.getDate() + " " + days[hoje_4.getDay()];

		new Chart(document.getElementById("myChart"), {
			  type: 'line',
			  data: {
			    labels: [hoje_4,hoje_3,hoje_2,hoje_1,hoje],
			    datasets: [{ 
			        data: [{{$views_hoje_4}},{{$views_hoje_3}},{{$views_hoje_2}},{{$views_hoje_1}},{{$views_hoje}}],
			        label: "Número de Visualizações",
			        borderColor: "#3e95cd",
			        fill: false
			      }
			    ]
			  },
			  options: {
			    title: {
			      display: true,
			      // text: 'World population per region (in millions)'
			    }
			  }
		});
	</script>
@stop