app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::resource('admin/users', 'AdminUsersController');

routes/web.php
<?php

use App\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });

// Route::get('verify/{email}/{verifyToken}','Auth\RegisterController@sendEmailDone')->name('sendEmailDone');

Route::get('verify/{email}/{verifyToken}',function($email, $verifyToken){

	$user = User::where('email',$email)->first();
        
    if($user){
        user::where('email',$email)->update(['is_active'=>'1', 'verifyToken'=>null]);

        Session::flash('success_validar_email', 'Conta ativada com sucesso!');

        return redirect('/');

    }else{
        return 'erro';
    }
})->name('sendEmailDone');

Route::auth();

Route::get('/', 'IndexController@index');

Route::get('/home', 'IndexController@index');

Route::middleware(['inscrito'])->group(function () {
    Route::get('user', 'UserController@index');
    Route::get('user/edit', 'UserController@edit');
    Route::get('user/update', 'UserController@update');
    Route::resource('user', 'UserController');
});

Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['middleware'=>'admin'], function(){
	
	Route::get('/admin', 'AdminController@index');

	Route::resource('admin/users', 'AdminUsersController');

	Route::resource('admin/redessociais', 'RedesSociaisController');

	Route::resource('admin/posts', 'AdminPostsController');

	Route::resource('admin/categories', 'AdminCategoriesController');

	Route::resource('admin/comments', 'PostCommentsController');

	Route::resource('admin/comment/replies', 'CommentRepliesController');

	Route::resource('admin/quemsomos', 'QuemSomosController');

});

Route::get('/post/{id}', ['as'=>'home.post', 'uses'=>'AdminPostsController@post']); // as nomeia a rota

Route::get('send', 'ContatoController@send');

Route::get('fale_conosco',function(){

	return view('fale_conosco');
});

Route::post('enviar', 'ContatoController@enviaContato');


Route::get('/curtir_post/', ['as'=>'curtir_post', 'uses'=>'UserController@curtir']); // as nomeia a rota

Route::get('/descurtir_post', ['as'=>'descurtir_post', 'uses'=>'UserController@descurtir']); // as nomeia a rota


Route::resource('comments', 'PostCommentsController');

Route::resource('replies', 'CommentRepliesController');

Route::resource('comments', 'PostCommentsController');

Route::get('/category/{id}', ['as'=>'category', 'uses'=>'IndexController@categories']); // as nomeia a rota

Route::get('/quemsomos', ['as'=>'quemsomos', 'uses'=>'IndexController@index_quemsomos']); // as nomeia a rota

Route::post('/more_posts', 'IndexController@more_posts');


Route::get('search_ajax_post', 'IndexController@search_ajax_post');

Route::get('/search_post/', ['as'=>'search_post','uses'=>'IndexController@search_post']);

//Routes to social login
Route::post('/login/social', 'Auth\LoginController@loginSocial');

Route::get('/login/callback', 'Auth\LoginController@loginCallback');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'verifyToken', 'name', 'email', 'password', 'role_id', 'is_active', 'photo_id','facebook','twitter','instagram','pinterest','about',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role(){
        return $this->belongsTo('App\Role');
    }

    public function photo(){
        return $this->belongsTo('App\Photo');
    }

    public function post(){
        return $this->hasMany('App\Post');
    }
    
    public function comments(){
        return $this->hasMany('App\Comment');
    }

    public function likes_posts(){
        return $this->belongsToMany('App\Post');
    }

    //Se o role for Admin
    public function isAdmin(){
        if(isset($this->role->name) and $this->role->name == 'Admin' and $this->is_active == 1){
            return true;
        }else{
            return false;
        }
    }

    public function isInscrito(){
        if(isset($this->role->name) and $this->role->name == 'Inscrito' and $this->is_active == 1){
            return true;
        }else{
            return false;
        }
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

use App\Http\Requests\UserEditInscrito;

use App\Http\Requests;
use App\Http\Requests\UsersRequest;
use App\Http\Requests\UsersEditRequest;

use App\Post;
use App\Category;
use App\QuemSomos;
use App\User;
use App\Photo;
use App\RedesSociais;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $user = Auth::user();

        $posts = User::find($user->id)->likes_posts()->paginate(7);

        return view('user.index', compact('user', 'posts'));      
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        //

        $user = Auth::user();

        return view('user.edit', compact('user'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserEditInscrito $request, $id)
    {
        //

        $user = Auth::user();

        if( ($request->password == '') or ( bcrypt($request->password) == $user->password )){
            
            $input = $request->except('password');
               
        }else{

            $input = $request->all();

            $input['password'] = bcrypt($request->password); 
        }

        if($input['email'] != $user->email){
            $this->validate($request, [
                'email' => 'unique:users',
            ]);           
        }
        

        if($file = $request->file('photo_id')){ //coloca o file entro do request no $file

            $name = time() . $file->getClientOriginalName(); //cria o nome da imagem com a hora e o nome

            $file->move('images', $name); // move o $file dentro da pasta images

            $photo = Photo::create(['file'=>$name]); //insert na tabela Photo e coloca esse registro dentro de $photo

            $input['photo_id'] = $photo->id; //coloca a id do regitro acima dentro do input photo_id

        }

        $user->update($input);

        Session::flash('success', 'Usuário atualizado com sucesso!');

        return redirect()->back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function curtir(Request $request){

        $user = Auth::user();

        $input = $request->all();

        // $input['created_at'] = date("Y-m-d H:i:s"); 

        $user->likes_posts()->attach($input);

        // return redirect()->back();
        return response()->json(['success'=>'Curtido com sucesso']);


        
    }

    public function descurtir(Request $request){

        $user = Auth::user();

        $input = $request->all();

        // $input['created_at'] = date("Y-m-d H:i:s"); 

        $user->likes_posts()->detach($input);

        // return redirect()->back();
        return response()->json(['success'=>'Descurtido com sucesso']);
        
    }

}

app/Http/Controllers/_UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

use App\Http\Requests\UserEditInscrito;

use App\Http\Requests;
use App\Http\Requests\UsersRequest;
use App\Http\Requests\UsersEditRequest;

use App\Post;
use App\Category;
use App\QuemSomos;
use App\User;
use App\Photo;
use App\RedesSociais;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $user = Auth::user();

        return view('user.index', compact('user'));      
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        //

        $user = Auth::user();

        return view('user.edit', compact('user'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserEditInscrito $request, $id)
    {
        //

        $user = Auth::user();

        if( ($request->password == '') or ( bcrypt($request->password) == $user->password )){
            
            $input = $request->except('password');
               
        }else{

            $input = $request->all();

            $input['password'] = bcrypt($request->password); 
        }

        if($input['email'] != $user->email){
            $this->validate($request, [
                'email' => 'unique:users',
            ]);           
        }
        

        if($file = $request->file('photo_id')){ //coloca o file entro do request no $file

            $name = time() . $file->getClientOriginalName(); //cria o nome da imagem com a hora e o nome

            $file->move('images', $name); // move o $file dentro da pasta images

            $photo = Photo::create(['file'=>$name]); //insert na tabela Photo e coloca esse registro dentro de $photo

            $input['photo_id'] = $photo->id; //coloca a id do regitro acima dentro do input photo_id

        }

        $user->update($input);

        Session::flash('success', 'Usuário atualizado com sucesso!');

        return redirect()->back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function curtir(Request $request){

        $user = Auth::user();

        $input = $request->all();

        $user->likes_posts()->attach($input);

        return redirect()->back();
        
    }

}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@section('content')
	<h1>Create Users</h1>
	
	<div class="col-md-12">
		@include('include.form_error')
	</div>

	{!! Form::open(['method'=>'POST', 'action'=>'AdminUsersController@store', 'files'=>true]) !!}
		
		<div class="form-group">
			{!! Form::label('name', 'Title:') !!}
			{!! Form::text('name', null, ['class'=>'form-control']) !!}
		</div>

		<div class="form-group">
			{!! Form::label('email', 'Email:') !!}
			{!! Form::email('email', null, ['class'=>'form-control']) !!}			
		</div>

		<div class="form-group">
			{!! Form::label('role_id', 'Role:') !!}
			{!! Form::select('role_id', [''=>'Choose Options'] + $roles, null, ['class'=>'form-control']) !!}			
		</div>

		<div class="form-group">
			{!! Form::label('photo_id', 'File:') !!}
			{!! Form::file('photo_id', null, ['class'=>'form-control']) !!}			
		</div>

		<div class="form-group">
			{!! Form::label('is_active', 'Status:') !!}
			{!! Form::select('is_active', array(1 => 'Active', 0=> 'Not Active'), 0, ['class'=>'form-control']) !!}			
		</div>

		<div class="form-group">
			{!! Form::label('password', 'Password:') !!}
			{!! Form::password('password', ['class'=>'form-control']) !!}			
		</div>

		<div class="form-group">
			{!! Form::submit('Create User', ['class'=>'btn btn-primary']) !!}
		</div>
 
	{!! Form::close() !!}


@stop

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content')

	<h1>Edit Users</h1>

	<div class="col-sm-3">

		<img src="{{$user->photo ? $user->photo->file : 'http://placehold.it/400x400'}}" class="img-responsive img-rounded"></img>

	</div>

	<div class="col-sm-9">
		{!! Form::model($user, ['method'=>'PATCH', 'action'=>['AdminUsersController@update', $user->id], 'files'=>true]) !!}

			<div class="form-group">
				{!! Form::label('role_id', 'Role:') !!}
				{!! Form::select('role_id', [''=>'Choose Options'] + $roles, null, ['class'=>'form-control']) !!}			
			</div>

			<div class="form-group">
				{!! Form::label('is_active', 'Status:') !!}
				{!! Form::select('is_active', array(1 => 'Active', 0=> 'Not Active'), null, ['class'=>'form-control']) !!}			
			</div>

			<div class="form-group">
				{!! Form::submit('Update User', ['class'=>'btn btn-primary']) !!}
			</div>
	 
		{!! Form::close() !!}

		{!! Form::model($user, ['method'=>'DELETE', 'action'=>['AdminUsersController@destroy', $user->id,]]) !!}

			<div class="form-group">
				{!! Form::submit('Delete User', ['class'=>'btn btn-danger']) !!}
			</div>

		{!! Form::close() !!}		


	</div>

	
	<div class="col-md-12">
		@include('include.form_error')
	</div>
	


@stop

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')

	@if((session('success')))
		<p class="alert alert-success">{{session('success')}}</p>
	@endif
	

	<h1>Users</h1>

	<div class="col-md-12">

        @if (count($users) > 0)
            <section class="articles">
                @include('admin.users.load')
            </section>
        @endif

    </div>
    
	<script src="{{asset('js/libs.js')}}"></script>

    <script type="text/javascript">

        $(function() {
            $('body').on('click', '.pagination a', function(e) {
                e.preventDefault();

                $('#load a').css('color', '#dfecf6');
                $('#load').append('Carregando...');

                var url = $(this).attr('href');
                getArticles(url);
                window.history.pushState("", "", url);
            });

            function getArticles(url) {
                $.ajax({
                    url : url
                }).done(function (data) {
                    $('.articles').html(data);
                }).fail(function () {
                    alert('Articles could not be loaded.');
                });
            }
        });
    </script>

@stop

resources/views/admin/users/load.blade.php
<div id="load" style="position: relative;">
	<table class="table">
	    <thead>
	      <tr>
	        <th>Id</th>
	        <th>Photo</th>
	        <th>Name</th>
	        <th>Email</th>
	        <th>Role</th>
	        <th>Active</th>
	        <th>Created</th>
	        <th>Updated</th>
	      </tr>
	    </thead>
	    <tbody>
	    	@if($users)
	    		@foreach ($users as $user)
	    			<tr>
				    	<td>{{$user->id}}</td>
				    	<td><img style="height:50px;" src="{{$user->photo ? $user->photo->file : 'http://placehold.it/400x400'}}" class="img-responsive img-rounded"></img></td>
				        <td><a href="{{route('users.edit', $user->id)}}">{{$user->name}}</a></td>
				        <td>{{$user->email}}</td>
				        <td>{{isset($user->role->name) ? $user->role->name : 'User has no role' }}</td>
				        <td>{{$user->is_active == 1 ? 'Active' : 'No active'}}</td>
				        <td>{{$user->created_at->diffForHumans()}}</td>
				        <td>{{$user->updated_at->diffForHumans()}}</td>
				    </tr>	     
	    		@endforeach
	    	@endif
	      
	    </tbody>
	</table>
</div>
{{ $users->links() }}