app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::resource('admin/users', 'AdminUsersController');

routes/web.php
<?php

use App\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });

// Route::get('verify/{email}/{verifyToken}','Auth\RegisterController@sendEmailDone')->name('sendEmailDone');

Route::get('verify/{email}/{verifyToken}',function($email, $verifyToken){

	$user = User::where('email',$email)->first();
        
    if($user){
        user::where('email',$email)->update(['is_active'=>'1', 'verifyToken'=>null]);

        Session::flash('success_validar_email', 'Conta ativada com sucesso!');

        return redirect('/');

    }else{
        return 'erro';
    }
})->name('sendEmailDone');

Route::auth();

Route::get('/', 'IndexController@index');

Route::get('/home', 'IndexController@index');

Route::middleware(['inscrito'])->group(function () {
    Route::get('user', 'UserController@index');
    Route::get('user/edit', 'UserController@edit');
    Route::get('user/update', 'UserController@update');
    Route::resource('user', 'UserController');
});

Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['middleware'=>'admin'], function(){
	
	Route::get('/admin', 'AdminController@index');

	Route::resource('admin/users', 'AdminUsersController');

	Route::resource('admin/redessociais', 'RedesSociaisController');

	Route::resource('admin/posts', 'AdminPostsController');

	Route::resource('admin/categories', 'AdminCategoriesController');

	Route::resource('admin/comments', 'PostCommentsController');

	Route::resource('admin/comment/replies', 'CommentRepliesController');

	Route::resource('admin/quemsomos', 'QuemSomosController');

});

Route::get('/post/{id}', ['as'=>'home.post', 'uses'=>'AdminPostsController@post']); // as nomeia a rota

Route::get('send', 'ContatoController@send');

Route::get('fale_conosco',function(){

	return view('fale_conosco');
});

Route::post('enviar', 'ContatoController@enviaContato');


Route::get('/curtir_post/', ['as'=>'curtir_post', 'uses'=>'UserController@curtir']); // as nomeia a rota

Route::get('/descurtir_post', ['as'=>'descurtir_post', 'uses'=>'UserController@descurtir']); // as nomeia a rota


Route::resource('comments', 'PostCommentsController');

Route::resource('replies', 'CommentRepliesController');

Route::resource('comments', 'PostCommentsController');

Route::get('/category/{id}', ['as'=>'category', 'uses'=>'IndexController@categories']); // as nomeia a rota

Route::get('/quemsomos', ['as'=>'quemsomos', 'uses'=>'IndexController@index_quemsomos']); // as nomeia a rota

Route::post('/more_posts', 'IndexController@more_posts');


Route::get('search_ajax_post', 'IndexController@search_ajax_post');

Route::get('/search_post/', ['as'=>'search_post','uses'=>'IndexController@search_post']);

//Routes to social login
Route::post('/login/social', 'Auth\LoginController@loginSocial');

Route::get('/login/callback', 'Auth\LoginController@loginCallback');

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{asset('css/app.css')}}" rel="stylesheet">

    <link href="{{asset('css/libs.css')}}" rel="stylesheet">


</head>

<body id="admin-page">

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">Home</a>
        </div>
        <!-- /.navbar-header -->



        <ul class="nav navbar-top-links navbar-right">


            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    {{ auth()->user()->name }}
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="{{url('/')}}"><i class="fa fa-newspaper-o"></i> Blog</a>
                    </li>
                    <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                    </li>
                    <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="{{ url('/logout') }}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->


        </ul>






        {{--<ul class="nav navbar-nav navbar-right">--}}
        {{--@if(auth()->guest())--}}
        {{--@if(!Request::is('auth/login'))--}}
        {{--<li><a href="{{ url('/auth/login') }}">Login</a></li>--}}
        {{--@endif--}}
        {{--@if(!Request::is('auth/register'))--}}
        {{--<li><a href="{{ url('/auth/register') }}">Register</a></li>--}}
        {{--@endif--}}
        {{--@else--}}
        {{--<li class="dropdown">--}}
        {{--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ auth()->user()->name }} <span class="caret"></span></a>--}}
        {{--<ul class="dropdown-menu" role="menu">--}}
        {{--<li><a href="{{ url('/auth/logout') }}">Logout</a></li>--}}

        {{--<li><a href="{{ url('/admin/profile') }}/{{auth()->user()->id}}">Profile</a></li>--}}
        {{--</ul>--}}
        {{--</li>--}}
        {{--@endif--}}
        {{--</ul>--}}





        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                        </div>
                        <!-- /input-group -->
                    </li>
                    <li>
                        <a href="/admin"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-wrench fa-fw"></i>Users<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{{ route('users.index') }}">All Users</a>
                            </li>

                            <li>
                                <a href="{{ route('users.create') }}">Create User</a>
                            </li>

                        </ul>
                        <!-- /.nav-second-level -->
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-wrench fa-fw"></i> Posts<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{{route('posts.index')}}">All Posts</a>
                            </li>

                            <li>
                                <a href="{{route('posts.create')}}">Create Post</a>
                            </li>
                            <li>
                                <a href="{{route('comments.index')}}">All Comments</a>
                            </li>  
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-wrench fa-fw"></i>Categories<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{{route('categories.index')}}">All Categories</a>
                            </li>

                            <li>
                                <a href="{{route('categories.create')}}">Create Category</a>
                            </li>

                        </ul>
                        <!-- /.nav-second-level -->
                    </li>


                    <li>
                        <a href="#"><i class="fa fa-wrench fa-fw"></i>Quem Somos<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{{route('quemsomos.index')}}">Quem Somos</a>
                            </li>

                        </ul>
                        <!-- /.nav-second-level -->
                    </li>

                    <li>
                        <a href="#"><i class="fa fa-wrench fa-fw"></i>Redes Sociais<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{{route('redessociais.index')}}">Lista</a>
                            </li>
                            <li>
                                <a href="{{route('redessociais.create')}}">Criar</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>

                </ul>


            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>





    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <a href="/profile"><i class="fa fa-dashboard fa-fw"></i>Profile</a>
                </li>




                <li>
                    <a href="#"><i class="fa fa-wrench fa-fw"></i> Posts<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                            <a href="">All Posts</a>
                        </li>

                        <li>
                            <a href="">Create Post</a>
                        </li>

                    </ul>
                    <!-- /.nav-second-level -->
                </li>





            </ul>

        </div>

    </div>

</div>






<!-- Page Content -->
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header"></h1>

                @yield('content')
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

<!-- jQuery -->
<script src="{{asset('js/libs.js')}}"></script>

  <script type="text/javascript" src="http://js.nicedit.com/nicEdit-latest.js"></script> <script type="text/javascript">
//<![CDATA[
        bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
  //]]>
  </script>

@yield('footer')


<script type="text/javascript">
    
   
    

</script>


</body>

</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title></title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Laravel
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/home') }}">Home</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js" integrity="sha384-I6F5OKECLVtK/BL+8iSLDEHowSAfUo76ZL9+kGAgTRdiByINKJaqTPH/QVNS1VDb" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}

</body>
</html>

resources/views/layouts/blog-home.blade.php
@include('include.head')

<body>

    <!-- Navigation -->

    @include('include.menu')

    @yield('header')

    <div class="container margin-top-big">

      @if(Auth::user() and Auth::user()->is_active == 0) 
        <div class="col-md-12">
          <div class="alert alert-warning" role="alert">
            Acesse seu email para validar sua conta
          </div>
        </div>              
      @endif

      @if((session('success_validar_email')))
         <div class="col-md-12">
          <div class="alert alert-success" role="alert">
            {{session('success_validar_email')}}
          </div>
        </div>
      @endif  
      
        <div class="row">
          @yield('content')
        </div>
    </div>

    <footer>
        @include('include.footer')
    </footer>
     <!-- jQuery -->
    <script src="{{asset('js/libs.js')}}"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>

    <script>
      $( function() {

         $(window).on('scroll', function(e){
              //aparece segundo menu
              if($(this).scrollTop() == 0){
                  
              }else{
                  
              }

          });            

        $('.slide').slick({
          autoplay: true,
          dots: true,
          infinite: true,
          speed: 500,
          slidesToShow: 1,
          adaptiveHeight: true
        });

        $(".dropdown-toggle").dropdown();
        
      } );      

    </script>
</body>

</html>

resources/views/layouts/blog-post.blade.php
@include('include.head')

<body>

    <!-- Navigation -->

    @include('include.menu')


    <!-- Page Content -->
    <div class="container margin-top-big">

        <div class="row">
            @if(Auth::user() and Auth::user()->is_active == 0) 
                <div class="col-md-12">
                  <div class="alert alert-warning" role="alert">
                    Acesse seu email para validar sua conta
                  </div>
                </div>              
            @endif
            <!-- Blog Post Content Column -->
            <div class="col-md-8 postagem">
                @yield('content')
            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">
              
                @include('include.aside')
                
                @include('include.user_admin')
                
            </div>

        </div>
        <!-- /.row -->        

    </div>
    <!-- /.container -->
    <!-- Footer -->
    <footer>
        @include('include.footer')
    </footer>

    <script src="{{asset('js/libs.js')}}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
      $( function() {
        
        $("#searchItem").autocomplete({
          source: 'http://dry-hollows-38671.herokuapp.com/search_ajax_post'
        });

        $(".dropdown-toggle").dropdown();

      });
    </script> 

</body>

</html>