app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::resource('admin/users', 'AdminUsersController');

routes/web.php
<?php

use App\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });

// Route::get('verify/{email}/{verifyToken}','Auth\RegisterController@sendEmailDone')->name('sendEmailDone');

Route::get('verify/{email}/{verifyToken}',function($email, $verifyToken){

	$user = User::where('email',$email)->first();
        
    if($user){
        user::where('email',$email)->update(['is_active'=>'1', 'verifyToken'=>null]);

        Session::flash('success_validar_email', 'Conta ativada com sucesso!');

        return redirect('/');

    }else{
        return 'erro';
    }
})->name('sendEmailDone');

Route::auth();

Route::get('/', 'IndexController@index');

Route::get('/home', 'IndexController@index');

Route::middleware(['inscrito'])->group(function () {
    Route::get('user', 'UserController@index');
    Route::get('user/edit', 'UserController@edit');
    Route::get('user/update', 'UserController@update');
    Route::resource('user', 'UserController');
});

Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['middleware'=>'admin'], function(){
	
	Route::get('/admin', 'AdminController@index');

	Route::resource('admin/users', 'AdminUsersController');

	Route::resource('admin/redessociais', 'RedesSociaisController');

	Route::resource('admin/posts', 'AdminPostsController');

	Route::resource('admin/categories', 'AdminCategoriesController');

	Route::resource('admin/comments', 'PostCommentsController');

	Route::resource('admin/comment/replies', 'CommentRepliesController');

	Route::resource('admin/quemsomos', 'QuemSomosController');

});

Route::get('/post/{id}', ['as'=>'home.post', 'uses'=>'AdminPostsController@post']); // as nomeia a rota

Route::get('send', 'ContatoController@send');

Route::get('fale_conosco',function(){

	return view('fale_conosco');
});

Route::post('enviar', 'ContatoController@enviaContato');


Route::get('/curtir_post/', ['as'=>'curtir_post', 'uses'=>'UserController@curtir']); // as nomeia a rota

Route::get('/descurtir_post', ['as'=>'descurtir_post', 'uses'=>'UserController@descurtir']); // as nomeia a rota


Route::resource('comments', 'PostCommentsController');

Route::resource('replies', 'CommentRepliesController');

Route::resource('comments', 'PostCommentsController');

Route::get('/category/{id}', ['as'=>'category', 'uses'=>'IndexController@categories']); // as nomeia a rota

Route::get('/quemsomos', ['as'=>'quemsomos', 'uses'=>'IndexController@index_quemsomos']); // as nomeia a rota

Route::post('/more_posts', 'IndexController@more_posts');


Route::get('search_ajax_post', 'IndexController@search_ajax_post');

Route::get('/search_post/', ['as'=>'search_post','uses'=>'IndexController@search_post']);

//Routes to social login
Route::post('/login/social', 'Auth\LoginController@loginSocial');

Route::get('/login/callback', 'Auth\LoginController@loginCallback');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
	protected $fillable = [
		'name'
	];

	public function posts(){
        return $this->hasMany('App\Post');
    }
	
}

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('content')

	<h1>Edit Categories</h1>

	<div class="col-md-6">
		{!! Form::model($category, ['method'=>'PATCH', 'action'=>['AdminCategoriesController@update', $category->id]]) !!}
			<div class="form-group">
				{!! Form::label('name', 'Category:') !!}
				{!! Form::text('name', null, ['class'=>'form-control']) !!}
			</div>
			<div class="form-group">
				{!! Form::submit('Update Category', ['class'=>'btn btn-primary']) !!}
			</div>
		{!! Form::close() !!}

		{!! Form::model($category, ['method'=>'DELETE', 'action'=>['AdminCategoriesController@destroy', $category->id]]) !!}
			{!! Form::submit('Delete Category', ['class'=>'btn btn-danger']) !!}
		{!! Form::close() !!}

	</div>

@stop

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('content')

	<h1>Categories</h1>

	<div class="col-md-6">
		{!! Form::open(['method'=>'POST', 'action'=>'AdminCategoriesController@store']) !!}
			<div class="form-group">
				{!! Form::label('name', 'Category:') !!}
				{!! Form::text('name', null, ['class'=>'form-control']) !!}
			</div>
			<div class="form-group">
				{!! Form::submit('Create Category', ['class'=>'btn btn-primary']) !!}
			</div>
		{!!  Form::close() !!}
	</div>

	<div class="col-md-6">
		<table class="table">
		    <thead>
		      <tr>
		        <th>Id</th>
		        <th>Category</th>
		        <th>Created</th>
		        <th>Updated</th>
		      </tr>
		    </thead>
		    <tbody>
		    	@if($categories)
		    		@foreach ($categories as $category)
		    			<tr>
					    	<td>{{$category->id}}</td>
					    	<td><a href="{{route('categories.edit', $category->id)}}">{{$category->name}}</a></td>
					        <td>{{$category->created_at->diffForHumans()}}</td>
					        <td>{{$category->updated_at->diffForHumans()}}</td>
					    </tr>	     
		    		@endforeach
		    	@endif
		      
		    </tbody>
		</table>
	</div>
	

@stop